const PROGRESSIVE_WEB_APPS = 'PROGRESSIVE WEB APPS';
const REACT_POWERED_WEBSITES = 'REACT POWERED WEBSITES';
const CHROME_EXTENSIONS = 'CHROME EXTENSIONS';
const OPTIMIZE_PERFORMANCE_FOR_YOUR_WEB_APPS = 'OPTIMIZE PERFORMANCE FOR YOUR WEB APPS';
const RESPONSIVE_WEB_LAYOUTS = 'RESPONSIVE WEB LAYOUTS'

export const TYPE_WRITER_STRINGS = [
    PROGRESSIVE_WEB_APPS,
    REACT_POWERED_WEBSITES,
    CHROME_EXTENSIONS,
    OPTIMIZE_PERFORMANCE_FOR_YOUR_WEB_APPS,
    RESPONSIVE_WEB_LAYOUTS,
];
